name: Build
on:
  release:
    types: [prereleased]
  push:
    branches: [main]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write


jobs:
  deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        arch: [amd64]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source file
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.21'

      - name: Go module tidy
        run: go mod tidy

      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build Unix-Like
        if: matrix.platform != 'windows-latest'
        run: go build -o torch-backend.srv -v ./main.go

      - name: Linux - Uploading Artifact
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@master
        with:
          #name: torch-backend-${{ github.sha }}.ubuntu-${{ matrix.arch }}
          name: torch-backend.srv
          path: torch-backend.srv

      - name: Linux - Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        if: github.event_name == 'release' && matrix.platform == 'ubuntu-latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: torch-backend.srv
          asset_name: torch-backend.srv
          tag: ${{ github.ref }}
          overwrite: true
